import React from "react";

function Sample() {
  return (
    <div id="sample" className="w3-container">
      <h2>Sample</h2>
      <p>
        <i>
          Although the default output when you load this page is a single
          sentence, the site is intended to be a fully functional lorem ipsum
          generator. The following ten paragraphs are an example of the output
          that might be generated by entering 10 as the number of paragraphs and
          5 as the number of sentences.
        </i>
      </p>
      <p>
        We'll make some big ol' huge mountains! There's too many complicated
        things in our life already. All you're worried about is this nice
        outside shape. Always follow the angles. Don't just cover it all up --
        leave these spots!
      </p>
      <p>
        Everybody should have a friend. Just sorta make these things up in your
        mind, and let them drop in. Help them make a happy buck or two. Sort of
        an orangy-yellowish color. Water breaks, and it churns, and it has fun!
      </p>
      <p>
        Today's such a wonderful day, let's just make a happy little painting.
        Maybe I'll have a bit mountain today. You can do anything that you
        believe you can do. Get it to where you want it, and leave it alone.
        That's the fun part of this whole technique.
      </p>
      <p>
        Don't over do it -- be careful. Be careful. Always start with a clean
        brush in a light area and work outward. We planned this son-of-a-gun
        right from the beginning. People are so excited when they see this
        happen. Everybody will see nature through different eyes.
      </p>
      <p>
        Let's make some happy little clouds in our world. Be sure it's odorless
        or you'll be working by yourself. A half a hair and some air. Let's
        build us a little cloud. I lived in Alaska for many, many years.
      </p>
      <p>
        Begin laying in just some beautiful little highlights. We'll just sort
        of see what happens. The round brush is so fun, let's go back to that.
        Just make little X's, and we'll put in a happy little sky. Always keep
        the brush moving.
      </p>
      <p>
        If there's a secret to anything, it's practice. It's easy to add more
        color, but it's a son of a gun to take it away. Absolutely no limits!
        You know me, I get crazy. Follow these angles.
      </p>
      <p>
        Now we'll fluff it. Do a cabin-ectomy. There's some little stringy ones
        that live down here. There's nothing worse than an angry tree. I think
        you'll be tickled with what you can do with something that starts out
        looking this bad.
      </p>
      <p>
        I like the mountains -- they're my favorite. Zooooom... you've gotta
        make the little noises or it doesn't work right. Let's build a happy
        little cloud in the sky. You can do it! We are really trying to teach
        you a technique. We're not trying to teach you to copy.
      </p>
      <p>
        Let's have some fun! If you're going to knock a wasp's nest down, you
        run. Big buildings are just little buildings that had a shot of
        vitamins. We're ready to get serious with this. We can stir this up a
        little bit.
      </p>
    </div>
  );
}

export default Sample;
